apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: code-with-quarkus-kcd
  labels:
    app: code-with-quarkus-kcd
spec:
  host: code-with-quarkus-kcd.apps.cluster-ln4rj.ln4rj.sandbox234.opentlc.com
  to:
    kind: Service
    name: code-with-quarkus-kcd
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
