apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - route.yaml

images:
  - name: quarkus
    newName: image-registry.openshift-image-registry.svc:5000/kcd-lima/code-with-quarkus-kcd
    newTag: 1.0.0
