apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: code-with-quarkus-kcd
  labels:
    app: code-with-quarkus-kcd
spec:
  host: code-with-quarkus-kcd45.apps.cluster-mvf62.mvf62.sandbox2472.opentlc.com
  to:
    kind: Service
    name: code-with-quarkus-kcd
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
